//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLearner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output.txt")]
        public string File {
            get {
                return ((string)(this["File"]));
            }
            set {
                this["File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedAlgorithm {
            get {
                return ((int)(this["SelectedAlgorithm"]));
            }
            set {
                this["SelectedAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOUGA_PDDLOutput {
            get {
                return ((bool)(this["LOUGA_PDDLOutput"]));
            }
            set {
                this["LOUGA_PDDLOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOUGA_GoalStateComplete {
            get {
                return ((bool)(this["LOUGA_GoalStateComplete"]));
            }
            set {
                this["LOUGA_GoalStateComplete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LOUGA_PopulationSize {
            get {
                return ((int)(this["LOUGA_PopulationSize"]));
            }
            set {
                this["LOUGA_PopulationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int LOUGA_GenerationsCount {
            get {
                return ((int)(this["LOUGA_GenerationsCount"]));
            }
            set {
                this["LOUGA_GenerationsCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int LOUGA_GreedySearchTreshold {
            get {
                return ((int)(this["LOUGA_GreedySearchTreshold"]));
            }
            set {
                this["LOUGA_GreedySearchTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LOUGA_PopulationRestartTreshold {
            get {
                return ((int)(this["LOUGA_PopulationRestartTreshold"]));
            }
            set {
                this["LOUGA_PopulationRestartTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int LOUGA_CrossoverWithOldPopulationTreshold {
            get {
                return ((int)(this["LOUGA_CrossoverWithOldPopulationTreshold"]));
            }
            set {
                this["LOUGA_CrossoverWithOldPopulationTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int LOUGA_OldPopulationRestartTreshold {
            get {
                return ((int)(this["LOUGA_OldPopulationRestartTreshold"]));
            }
            set {
                this["LOUGA_OldPopulationRestartTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double ARMS_ProbabilityTreshold {
            get {
                return ((double)(this["ARMS_ProbabilityTreshold"]));
            }
            set {
                this["ARMS_ProbabilityTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double ARMS_MinActionConstraintWeight {
            get {
                return ((double)(this["ARMS_MinActionConstraintWeight"]));
            }
            set {
                this["ARMS_MinActionConstraintWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ARMS_MaxActionConstraintWeight {
            get {
                return ((double)(this["ARMS_MaxActionConstraintWeight"]));
            }
            set {
                this["ARMS_MaxActionConstraintWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double ARMS_InformationConstraintWeight {
            get {
                return ((double)(this["ARMS_InformationConstraintWeight"]));
            }
            set {
                this["ARMS_InformationConstraintWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GSAT")]
        public string ARMS_MaxSatAlgorithm {
            get {
                return ((string)(this["ARMS_MaxSatAlgorithm"]));
            }
            set {
                this["ARMS_MaxSatAlgorithm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int ARMS_MaxSatNumberOfTries {
            get {
                return ((int)(this["ARMS_MaxSatNumberOfTries"]));
            }
            set {
                this["ARMS_MaxSatNumberOfTries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int ARMS_MaxSatRestartTreshold {
            get {
                return ((int)(this["ARMS_MaxSatRestartTreshold"]));
            }
            set {
                this["ARMS_MaxSatRestartTreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double ARMS_MaxSatRandomChoiceProbability {
            get {
                return ((double)(this["ARMS_MaxSatRandomChoiceProbability"]));
            }
            set {
                this["ARMS_MaxSatRandomChoiceProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOUGA_EndAfterSolutionIsFound {
            get {
                return ((bool)(this["LOUGA_EndAfterSolutionIsFound"]));
            }
            set {
                this["LOUGA_EndAfterSolutionIsFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOUGA_PredicateByPredicate {
            get {
                return ((bool)(this["LOUGA_PredicateByPredicate"]));
            }
            set {
                this["LOUGA_PredicateByPredicate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LOUGA_MaxPredicateErrorRate {
            get {
                return ((double)(this["LOUGA_MaxPredicateErrorRate"]));
            }
            set {
                this["LOUGA_MaxPredicateErrorRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOUGA_GenerateNegativePreconditions {
            get {
                return ((bool)(this["LOUGA_GenerateNegativePreconditions"]));
            }
            set {
                this["LOUGA_GenerateNegativePreconditions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOUGA_GenerateCompletePreconditionsLists {
            get {
                return ((bool)(this["LOUGA_GenerateCompletePreconditionsLists"]));
            }
            set {
                this["LOUGA_GenerateCompletePreconditionsLists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LOUGA_ParametersCanRepeat {
            get {
                return ((bool)(this["LOUGA_ParametersCanRepeat"]));
            }
            set {
                this["LOUGA_ParametersCanRepeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double LOUGA_ObservationErrorWeight {
            get {
                return ((double)(this["LOUGA_ObservationErrorWeight"]));
            }
            set {
                this["LOUGA_ObservationErrorWeight"] = value;
            }
        }
    }
}
